version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sso-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sso_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sso-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # app:
  #   build: .
  #   container_name: sso-app
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - "44044:44044"
  #   environment:
  #     CONFIG_PATH: /app/config/local.yaml
  #   volumes:
  #     - ./configs:/app/configs
  #   networks:
  #     - sso-network

volumes:
  postgres-data:

networks:
  sso-network:
    driver: bridge